// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


String lastUpdated;
String lastUpdatedDOW;
String location;
float dewPointF;
float heatIndex;
float humidity;
float pressure_inHg;
float tempF;

void initProperties(){

  ArduinoCloud.addProperty(lastUpdated, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lastUpdatedDOW, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(location, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(dewPointF, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(heatIndex, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pressure_inHg, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tempF, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
